-- ============================================================================
-- Arrow Server - complete database schema
--
-- Generated by concatenating every Diesel migration up.sql file in
-- chronological order. Run against a fresh MySQL database BEFORE
-- `diesel migration run` is NOT required: the migration runner applies
-- the same statements itself. This file exists as a single-file reference
-- of the final schema.
--
-- Sections:
--   1. users               src/data/migrations/2025-11-22-113224-0000_user/up.sql
--   2. products            src/data/migrations/2025-11-27-104614-0000_products/up.sql
--   3. orders              src/data/migrations/2025-11-27-111653-0000_orders/up.sql
--   4. order_products      src/data/migrations/2025-11-27-115132-0000_order_products/up.sql
--   5. categories + product_categories
--                          src/data/migrations/2025-12-09-015731-0000_product_categories/up.sql
--   6. roles               src/data/migrations/2025-12-20-103925-0000_roles/up.sql
--   7. user_roles          src/data/migrations/2025-12-20-104256-0000_user_roles/up.sql
--   8. payment_status + nullable orders.user_id
--                          src/data/migrations/2026-08-07-164450-0000_payment_and_guest_orders/up.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. users
-- ----------------------------------------------------------------------------
CREATE TABLE `users` (
    `user_id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `password_hash` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

-- ----------------------------------------------------------------------------
-- 2. products
-- ----------------------------------------------------------------------------
CREATE TABLE `products` (
    product_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    product_image_uri VARCHAR(255),
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

-- ----------------------------------------------------------------------------
-- 3. orders
-- ----------------------------------------------------------------------------
CREATE TABLE `orders` (
    order_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
)

-- ----------------------------------------------------------------------------
-- 4. order_products
-- ----------------------------------------------------------------------------
CREATE TABLE `order_products` (
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(10, 2) NOT NULL,
    line_total DECIMAL(10, 2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
)

-- ----------------------------------------------------------------------------
-- 5. categories + product_categories
-- ----------------------------------------------------------------------------
CREATE TABLE `categories` (
    category_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `product_categories` (
    product_id INT NOT NULL,
    category_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (product_id, category_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(category_id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- 6. roles
-- ----------------------------------------------------------------------------
CREATE TABLE `roles` (
    role_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    permissions SET('READ', 'WRITE', 'DELETE', 'ADMIN') DEFAULT 'READ',
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

-- ----------------------------------------------------------------------------
-- 7. user_roles
-- ----------------------------------------------------------------------------
CREATE TABLE `user_roles` (
    role_id INT NOT NULL,
    user_id INT NOT NULL UNIQUE, -- Each user can have only one role
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES users(`user_id`) ON DELETE CASCADE,
    FOREIGN KEY (`role_id`) REFERENCES roles(`role_id`) ON DELETE CASCADE,
    PRIMARY KEY (`user_id`, `role_id`) -- Ensure a user cannot have the same role multiple times
);

-- ----------------------------------------------------------------------------
-- 8. payment_status + nullable orders.user_id (guest orders)
-- ----------------------------------------------------------------------------
ALTER TABLE orders MODIFY user_id INT NULL;
ALTER TABLE orders ADD COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid';
ALTER TABLE orders MODIFY status VARCHAR(50) NOT NULL DEFAULT 'Pending';
UPDATE orders SET status='Pending' WHERE status='pending';
