// Order logic goes here
// Users can place orders for products
// Users can view their order history
// Orders have statuses: Pending, Accepted, Completed, Cancelled
// Users can cancel their own orders if they are still pending
// Admins can update order statuses
// Users with WRITE permission can create and edit orders
// Users with READ permission can view only their own orders
// Admins can view and manage all orders
// Order total is calculated and auto generated by the db
