name: Trigger auto deployment for arrow-server-v1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ master ]
    paths:
    - '**'
    - '.github/workflows/arrow-server-v1-AutoDeployTrigger-2641f524-edcc-48ef-b656-c4eaf1376932.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARROWSERVERV1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ARROWSERVERV1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARROWSERVERV1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: schoolcontregistry.azurecr.io
          registryUsername: ${{ secrets.ARROWSERVERV1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ARROWSERVERV1_REGISTRY_PASSWORD }}
          containerAppName: arrow-server
          resourceGroup: school_group
          imageToBuild: schoolregistry.azurecr.io/arrow-server:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
